package com.content.train.dto.train;

import java.util.Date;

public class BaiduJoke {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.creator
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.modifier
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.create_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.modify_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.is_deleted
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.joke_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Date jokeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.text
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.img
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.title
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.type
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.user_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.thumbnail_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String thumbnailUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.category
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.sort
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.tag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.push_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Integer pushFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_baidu_api_joke.recommend_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String recommendFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.id
     *
     * @return the value of 3rd_baidu_api_joke.id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.id
     *
     * @param id the value for 3rd_baidu_api_joke.id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.creator
     *
     * @return the value of 3rd_baidu_api_joke.creator
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.creator
     *
     * @param creator the value for 3rd_baidu_api_joke.creator
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.modifier
     *
     * @return the value of 3rd_baidu_api_joke.modifier
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.modifier
     *
     * @param modifier the value for 3rd_baidu_api_joke.modifier
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.create_time
     *
     * @return the value of 3rd_baidu_api_joke.create_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.create_time
     *
     * @param createTime the value for 3rd_baidu_api_joke.create_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.modify_time
     *
     * @return the value of 3rd_baidu_api_joke.modify_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.modify_time
     *
     * @param modifyTime the value for 3rd_baidu_api_joke.modify_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.is_deleted
     *
     * @return the value of 3rd_baidu_api_joke.is_deleted
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.is_deleted
     *
     * @param isDeleted the value for 3rd_baidu_api_joke.is_deleted
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.joke_time
     *
     * @return the value of 3rd_baidu_api_joke.joke_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Date getJokeTime() {
        return jokeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.joke_time
     *
     * @param jokeTime the value for 3rd_baidu_api_joke.joke_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setJokeTime(Date jokeTime) {
        this.jokeTime = jokeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.text
     *
     * @return the value of 3rd_baidu_api_joke.text
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.text
     *
     * @param text the value for 3rd_baidu_api_joke.text
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.img
     *
     * @return the value of 3rd_baidu_api_joke.img
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.img
     *
     * @param img the value for 3rd_baidu_api_joke.img
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.title
     *
     * @return the value of 3rd_baidu_api_joke.title
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.title
     *
     * @param title the value for 3rd_baidu_api_joke.title
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.type
     *
     * @return the value of 3rd_baidu_api_joke.type
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.type
     *
     * @param type the value for 3rd_baidu_api_joke.type
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.user_id
     *
     * @return the value of 3rd_baidu_api_joke.user_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.user_id
     *
     * @param userId the value for 3rd_baidu_api_joke.user_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.thumbnail_url
     *
     * @return the value of 3rd_baidu_api_joke.thumbnail_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getThumbnailUrl() {
        return thumbnailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.thumbnail_url
     *
     * @param thumbnailUrl the value for 3rd_baidu_api_joke.thumbnail_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setThumbnailUrl(String thumbnailUrl) {
        this.thumbnailUrl = thumbnailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.category
     *
     * @return the value of 3rd_baidu_api_joke.category
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.category
     *
     * @param category the value for 3rd_baidu_api_joke.category
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.sort
     *
     * @return the value of 3rd_baidu_api_joke.sort
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.sort
     *
     * @param sort the value for 3rd_baidu_api_joke.sort
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setSort(String sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.tag
     *
     * @return the value of 3rd_baidu_api_joke.tag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.tag
     *
     * @param tag the value for 3rd_baidu_api_joke.tag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.push_flag
     *
     * @return the value of 3rd_baidu_api_joke.push_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Integer getPushFlag() {
        return pushFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.push_flag
     *
     * @param pushFlag the value for 3rd_baidu_api_joke.push_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setPushFlag(Integer pushFlag) {
        this.pushFlag = pushFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_baidu_api_joke.recommend_flag
     *
     * @return the value of 3rd_baidu_api_joke.recommend_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getRecommendFlag() {
        return recommendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_baidu_api_joke.recommend_flag
     *
     * @param recommendFlag the value for 3rd_baidu_api_joke.recommend_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setRecommendFlag(String recommendFlag) {
        this.recommendFlag = recommendFlag;
    }
}