package com.content.train.dto.train;

import java.util.Date;

import com.content.train.enums.BehaviorContent;
import lombok.Data;

public class ChanYouJi extends TitleSimilarAble{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.creator
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.modifier
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.create_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.modify_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.is_deleted
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.trip_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String tripId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.title
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.trip_days
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Integer tripDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.pic_count
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Integer picCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.like_count
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Integer likeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.view_count
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Integer viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.comment_count
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.trip_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String tripTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.img_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.wap_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String wapUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.sort
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.user_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.thumbnail_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String thumbnailUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.source
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.tag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.push_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Integer pushFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.recommend_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String recommendFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_chanyouji.content
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.id
     *
     * @return the value of 3rd_chanyouji.id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.id
     *
     * @param id the value for 3rd_chanyouji.id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.creator
     *
     * @return the value of 3rd_chanyouji.creator
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.creator
     *
     * @param creator the value for 3rd_chanyouji.creator
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.modifier
     *
     * @return the value of 3rd_chanyouji.modifier
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.modifier
     *
     * @param modifier the value for 3rd_chanyouji.modifier
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.create_time
     *
     * @return the value of 3rd_chanyouji.create_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.create_time
     *
     * @param createTime the value for 3rd_chanyouji.create_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.modify_time
     *
     * @return the value of 3rd_chanyouji.modify_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.modify_time
     *
     * @param modifyTime the value for 3rd_chanyouji.modify_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.is_deleted
     *
     * @return the value of 3rd_chanyouji.is_deleted
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.is_deleted
     *
     * @param isDeleted the value for 3rd_chanyouji.is_deleted
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.trip_id
     *
     * @return the value of 3rd_chanyouji.trip_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getTripId() {
        return tripId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.trip_id
     *
     * @param tripId the value for 3rd_chanyouji.trip_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setTripId(String tripId) {
        this.tripId = tripId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.title
     *
     * @return the value of 3rd_chanyouji.title
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.title
     *
     * @param title the value for 3rd_chanyouji.title
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.trip_days
     *
     * @return the value of 3rd_chanyouji.trip_days
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Integer getTripDays() {
        return tripDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.trip_days
     *
     * @param tripDays the value for 3rd_chanyouji.trip_days
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setTripDays(Integer tripDays) {
        this.tripDays = tripDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.pic_count
     *
     * @return the value of 3rd_chanyouji.pic_count
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Integer getPicCount() {
        return picCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.pic_count
     *
     * @param picCount the value for 3rd_chanyouji.pic_count
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setPicCount(Integer picCount) {
        this.picCount = picCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.like_count
     *
     * @return the value of 3rd_chanyouji.like_count
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.like_count
     *
     * @param likeCount the value for 3rd_chanyouji.like_count
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.view_count
     *
     * @return the value of 3rd_chanyouji.view_count
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.view_count
     *
     * @param viewCount the value for 3rd_chanyouji.view_count
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.comment_count
     *
     * @return the value of 3rd_chanyouji.comment_count
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.comment_count
     *
     * @param commentCount the value for 3rd_chanyouji.comment_count
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.trip_time
     *
     * @return the value of 3rd_chanyouji.trip_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getTripTime() {
        return tripTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.trip_time
     *
     * @param tripTime the value for 3rd_chanyouji.trip_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setTripTime(String tripTime) {
        this.tripTime = tripTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.img_url
     *
     * @return the value of 3rd_chanyouji.img_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.img_url
     *
     * @param imgUrl the value for 3rd_chanyouji.img_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.wap_url
     *
     * @return the value of 3rd_chanyouji.wap_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getWapUrl() {
        return wapUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.wap_url
     *
     * @param wapUrl the value for 3rd_chanyouji.wap_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setWapUrl(String wapUrl) {
        this.wapUrl = wapUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.sort
     *
     * @return the value of 3rd_chanyouji.sort
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.sort
     *
     * @param sort the value for 3rd_chanyouji.sort
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setSort(String sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.user_id
     *
     * @return the value of 3rd_chanyouji.user_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.user_id
     *
     * @param userId the value for 3rd_chanyouji.user_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.thumbnail_url
     *
     * @return the value of 3rd_chanyouji.thumbnail_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getThumbnailUrl() {
        return thumbnailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.thumbnail_url
     *
     * @param thumbnailUrl the value for 3rd_chanyouji.thumbnail_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setThumbnailUrl(String thumbnailUrl) {
        this.thumbnailUrl = thumbnailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.source
     *
     * @return the value of 3rd_chanyouji.source
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.source
     *
     * @param source the value for 3rd_chanyouji.source
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.tag
     *
     * @return the value of 3rd_chanyouji.tag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.tag
     *
     * @param tag the value for 3rd_chanyouji.tag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.push_flag
     *
     * @return the value of 3rd_chanyouji.push_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Integer getPushFlag() {
        return pushFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.push_flag
     *
     * @param pushFlag the value for 3rd_chanyouji.push_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setPushFlag(Integer pushFlag) {
        this.pushFlag = pushFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.recommend_flag
     *
     * @return the value of 3rd_chanyouji.recommend_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getRecommendFlag() {
        return recommendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.recommend_flag
     *
     * @param recommendFlag the value for 3rd_chanyouji.recommend_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setRecommendFlag(String recommendFlag) {
        this.recommendFlag = recommendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_chanyouji.content
     *
     * @return the value of 3rd_chanyouji.content
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_chanyouji.content
     *
     * @param content the value for 3rd_chanyouji.content
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    public String getTargetTitle() {
        return this.title;
    }

    public Integer getTargetTitleId() {
        return this.id;
    }

    public String getBehaviorId() {
        return BehaviorContent.TRIP.getPrefix()+this.id;
    }
}