package com.content.train.dto.train;

import java.util.Date;

public class ContentUserCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_user_count.id
     *
     * @mbggenerated Tue Aug 02 22:59:58 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_user_count.behavior_content
     *
     * @mbggenerated Tue Aug 02 22:59:58 CST 2016
     */
    private String behaviorContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_user_count.user_id_json
     *
     * @mbggenerated Tue Aug 02 22:59:58 CST 2016
     */
    private String userIdJson;


    private Date addTime;


    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_user_count.id
     *
     * @return the value of content_user_count.id
     *
     * @mbggenerated Tue Aug 02 22:59:58 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_user_count.id
     *
     * @param id the value for content_user_count.id
     *
     * @mbggenerated Tue Aug 02 22:59:58 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_user_count.behavior_content
     *
     * @return the value of content_user_count.behavior_content
     *
     * @mbggenerated Tue Aug 02 22:59:58 CST 2016
     */
    public String getBehaviorContent() {
        return behaviorContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_user_count.behavior_content
     *
     * @param behaviorContent the value for content_user_count.behavior_content
     *
     * @mbggenerated Tue Aug 02 22:59:58 CST 2016
     */
    public void setBehaviorContent(String behaviorContent) {
        this.behaviorContent = behaviorContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_user_count.user_id_json
     *
     * @return the value of content_user_count.user_id_json
     *
     * @mbggenerated Tue Aug 02 22:59:58 CST 2016
     */
    public String getUserIdJson() {
        return userIdJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_user_count.user_id_json
     *
     * @param userIdJson the value for content_user_count.user_id_json
     *
     * @mbggenerated Tue Aug 02 22:59:58 CST 2016
     */
    public void setUserIdJson(String userIdJson) {
        this.userIdJson = userIdJson;
    }
}