package com.content.train.dto.train;

import java.util.Date;

public class ItemSimiScore extends ItemSimiScoreKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_simi_score.target_item_id
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    private String targetItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_simi_score.add_date
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    private Date addDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_simi_score.target_item_id
     *
     * @return the value of item_simi_score.target_item_id
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    public String getTargetItemId() {
        return targetItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_simi_score.target_item_id
     *
     * @param targetItemId the value for item_simi_score.target_item_id
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    public void setTargetItemId(String targetItemId) {
        this.targetItemId = targetItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_simi_score.add_date
     *
     * @return the value of item_simi_score.add_date
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_simi_score.add_date
     *
     * @param addDate the value for item_simi_score.add_date
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
}