package com.content.train.dto.train;

public class ItemSimiScoreKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_simi_score.id
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_simi_score.item_id
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_simi_score.score
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    private Double score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_simi_score.id
     *
     * @return the value of item_simi_score.id
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_simi_score.id
     *
     * @param id the value for item_simi_score.id
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_simi_score.item_id
     *
     * @return the value of item_simi_score.item_id
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_simi_score.item_id
     *
     * @param itemId the value for item_simi_score.item_id
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_simi_score.score
     *
     * @return the value of item_simi_score.score
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_simi_score.score
     *
     * @param score the value for item_simi_score.score
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    public void setScore(Double score) {
        this.score = score;
    }
}