package com.content.train.dto.train;

import java.util.Date;
import lombok.Data;

public class MiaoPaiVideo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.creator
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.modifier
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.create_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.modify_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.is_deleted
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.title
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.username
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.user_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String userUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.img_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.wap_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String wapUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.video_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String videoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.category
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.like_count
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String likeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.time_duration
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String timeDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.src_type
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String srcType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.user_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.is_promotion
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String isPromotion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.thumbnail_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String thumbnailUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.tag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.push_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Integer pushFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_miaopai_video.recommend_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String recommendFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.id
     *
     * @return the value of 3rd_miaopai_video.id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.id
     *
     * @param id the value for 3rd_miaopai_video.id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.creator
     *
     * @return the value of 3rd_miaopai_video.creator
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.creator
     *
     * @param creator the value for 3rd_miaopai_video.creator
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.modifier
     *
     * @return the value of 3rd_miaopai_video.modifier
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.modifier
     *
     * @param modifier the value for 3rd_miaopai_video.modifier
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.create_time
     *
     * @return the value of 3rd_miaopai_video.create_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.create_time
     *
     * @param createTime the value for 3rd_miaopai_video.create_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.modify_time
     *
     * @return the value of 3rd_miaopai_video.modify_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.modify_time
     *
     * @param modifyTime the value for 3rd_miaopai_video.modify_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.is_deleted
     *
     * @return the value of 3rd_miaopai_video.is_deleted
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.is_deleted
     *
     * @param isDeleted the value for 3rd_miaopai_video.is_deleted
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.title
     *
     * @return the value of 3rd_miaopai_video.title
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.title
     *
     * @param title the value for 3rd_miaopai_video.title
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.username
     *
     * @return the value of 3rd_miaopai_video.username
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.username
     *
     * @param username the value for 3rd_miaopai_video.username
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.user_url
     *
     * @return the value of 3rd_miaopai_video.user_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getUserUrl() {
        return userUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.user_url
     *
     * @param userUrl the value for 3rd_miaopai_video.user_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setUserUrl(String userUrl) {
        this.userUrl = userUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.img_url
     *
     * @return the value of 3rd_miaopai_video.img_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.img_url
     *
     * @param imgUrl the value for 3rd_miaopai_video.img_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.wap_url
     *
     * @return the value of 3rd_miaopai_video.wap_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getWapUrl() {
        return wapUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.wap_url
     *
     * @param wapUrl the value for 3rd_miaopai_video.wap_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setWapUrl(String wapUrl) {
        this.wapUrl = wapUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.video_url
     *
     * @return the value of 3rd_miaopai_video.video_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.video_url
     *
     * @param videoUrl the value for 3rd_miaopai_video.video_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.category
     *
     * @return the value of 3rd_miaopai_video.category
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.category
     *
     * @param category the value for 3rd_miaopai_video.category
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.like_count
     *
     * @return the value of 3rd_miaopai_video.like_count
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.like_count
     *
     * @param likeCount the value for 3rd_miaopai_video.like_count
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setLikeCount(String likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.time_duration
     *
     * @return the value of 3rd_miaopai_video.time_duration
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getTimeDuration() {
        return timeDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.time_duration
     *
     * @param timeDuration the value for 3rd_miaopai_video.time_duration
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setTimeDuration(String timeDuration) {
        this.timeDuration = timeDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.src_type
     *
     * @return the value of 3rd_miaopai_video.src_type
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getSrcType() {
        return srcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.src_type
     *
     * @param srcType the value for 3rd_miaopai_video.src_type
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setSrcType(String srcType) {
        this.srcType = srcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.user_id
     *
     * @return the value of 3rd_miaopai_video.user_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.user_id
     *
     * @param userId the value for 3rd_miaopai_video.user_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.is_promotion
     *
     * @return the value of 3rd_miaopai_video.is_promotion
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getIsPromotion() {
        return isPromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.is_promotion
     *
     * @param isPromotion the value for 3rd_miaopai_video.is_promotion
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setIsPromotion(String isPromotion) {
        this.isPromotion = isPromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.thumbnail_url
     *
     * @return the value of 3rd_miaopai_video.thumbnail_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getThumbnailUrl() {
        return thumbnailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.thumbnail_url
     *
     * @param thumbnailUrl the value for 3rd_miaopai_video.thumbnail_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setThumbnailUrl(String thumbnailUrl) {
        this.thumbnailUrl = thumbnailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.tag
     *
     * @return the value of 3rd_miaopai_video.tag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.tag
     *
     * @param tag the value for 3rd_miaopai_video.tag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.push_flag
     *
     * @return the value of 3rd_miaopai_video.push_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Integer getPushFlag() {
        return pushFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.push_flag
     *
     * @param pushFlag the value for 3rd_miaopai_video.push_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setPushFlag(Integer pushFlag) {
        this.pushFlag = pushFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_miaopai_video.recommend_flag
     *
     * @return the value of 3rd_miaopai_video.recommend_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getRecommendFlag() {
        return recommendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_miaopai_video.recommend_flag
     *
     * @param recommendFlag the value for 3rd_miaopai_video.recommend_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setRecommendFlag(String recommendFlag) {
        this.recommendFlag = recommendFlag;
    }
}