package com.content.train.dto.train;

import java.util.Date;

import com.content.train.enums.BehaviorContent;
import lombok.Data;

public class SmZdm extends TitleSimilarAble{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.creator
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.modifier
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.create_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.modify_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.is_deleted
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_channel_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_channel_name
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleChannelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_title
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_date
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_format_date
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleFormatDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_pic
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articlePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_worthy
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleWorthy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_unworthy
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleUnworthy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_is_sold_out
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleIsSoldOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_is_timeout
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleIsTimeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_tag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_collection
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleCollection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_mall
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleMall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_comment
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_price
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articlePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.article_favorite
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String articleFavorite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.time_sort
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String timeSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.user_smzdm_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String userSmzdmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.tag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.sort
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.user_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.push_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private Integer pushFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.recommend_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String recommendFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 3rd_smzdm.content
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.id
     *
     * @return the value of 3rd_smzdm.id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.id
     *
     * @param id the value for 3rd_smzdm.id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.creator
     *
     * @return the value of 3rd_smzdm.creator
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.creator
     *
     * @param creator the value for 3rd_smzdm.creator
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.modifier
     *
     * @return the value of 3rd_smzdm.modifier
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.modifier
     *
     * @param modifier the value for 3rd_smzdm.modifier
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.create_time
     *
     * @return the value of 3rd_smzdm.create_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.create_time
     *
     * @param createTime the value for 3rd_smzdm.create_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.modify_time
     *
     * @return the value of 3rd_smzdm.modify_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.modify_time
     *
     * @param modifyTime the value for 3rd_smzdm.modify_time
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.is_deleted
     *
     * @return the value of 3rd_smzdm.is_deleted
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.is_deleted
     *
     * @param isDeleted the value for 3rd_smzdm.is_deleted
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_channel_id
     *
     * @return the value of 3rd_smzdm.article_channel_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleChannelId() {
        return articleChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_channel_id
     *
     * @param articleChannelId the value for 3rd_smzdm.article_channel_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleChannelId(String articleChannelId) {
        this.articleChannelId = articleChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_channel_name
     *
     * @return the value of 3rd_smzdm.article_channel_name
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleChannelName() {
        return articleChannelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_channel_name
     *
     * @param articleChannelName the value for 3rd_smzdm.article_channel_name
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleChannelName(String articleChannelName) {
        this.articleChannelName = articleChannelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_id
     *
     * @return the value of 3rd_smzdm.article_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_id
     *
     * @param articleId the value for 3rd_smzdm.article_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_title
     *
     * @return the value of 3rd_smzdm.article_title
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_title
     *
     * @param articleTitle the value for 3rd_smzdm.article_title
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_date
     *
     * @return the value of 3rd_smzdm.article_date
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleDate() {
        return articleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_date
     *
     * @param articleDate the value for 3rd_smzdm.article_date
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleDate(String articleDate) {
        this.articleDate = articleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_format_date
     *
     * @return the value of 3rd_smzdm.article_format_date
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleFormatDate() {
        return articleFormatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_format_date
     *
     * @param articleFormatDate the value for 3rd_smzdm.article_format_date
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleFormatDate(String articleFormatDate) {
        this.articleFormatDate = articleFormatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_pic
     *
     * @return the value of 3rd_smzdm.article_pic
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticlePic() {
        return articlePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_pic
     *
     * @param articlePic the value for 3rd_smzdm.article_pic
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticlePic(String articlePic) {
        this.articlePic = articlePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_worthy
     *
     * @return the value of 3rd_smzdm.article_worthy
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleWorthy() {
        return articleWorthy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_worthy
     *
     * @param articleWorthy the value for 3rd_smzdm.article_worthy
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleWorthy(String articleWorthy) {
        this.articleWorthy = articleWorthy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_unworthy
     *
     * @return the value of 3rd_smzdm.article_unworthy
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleUnworthy() {
        return articleUnworthy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_unworthy
     *
     * @param articleUnworthy the value for 3rd_smzdm.article_unworthy
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleUnworthy(String articleUnworthy) {
        this.articleUnworthy = articleUnworthy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_is_sold_out
     *
     * @return the value of 3rd_smzdm.article_is_sold_out
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleIsSoldOut() {
        return articleIsSoldOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_is_sold_out
     *
     * @param articleIsSoldOut the value for 3rd_smzdm.article_is_sold_out
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleIsSoldOut(String articleIsSoldOut) {
        this.articleIsSoldOut = articleIsSoldOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_is_timeout
     *
     * @return the value of 3rd_smzdm.article_is_timeout
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleIsTimeout() {
        return articleIsTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_is_timeout
     *
     * @param articleIsTimeout the value for 3rd_smzdm.article_is_timeout
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleIsTimeout(String articleIsTimeout) {
        this.articleIsTimeout = articleIsTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_tag
     *
     * @return the value of 3rd_smzdm.article_tag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleTag() {
        return articleTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_tag
     *
     * @param articleTag the value for 3rd_smzdm.article_tag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleTag(String articleTag) {
        this.articleTag = articleTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_collection
     *
     * @return the value of 3rd_smzdm.article_collection
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleCollection() {
        return articleCollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_collection
     *
     * @param articleCollection the value for 3rd_smzdm.article_collection
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleCollection(String articleCollection) {
        this.articleCollection = articleCollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_mall
     *
     * @return the value of 3rd_smzdm.article_mall
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleMall() {
        return articleMall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_mall
     *
     * @param articleMall the value for 3rd_smzdm.article_mall
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleMall(String articleMall) {
        this.articleMall = articleMall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_comment
     *
     * @return the value of 3rd_smzdm.article_comment
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleComment() {
        return articleComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_comment
     *
     * @param articleComment the value for 3rd_smzdm.article_comment
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleComment(String articleComment) {
        this.articleComment = articleComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_url
     *
     * @return the value of 3rd_smzdm.article_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleUrl() {
        return articleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_url
     *
     * @param articleUrl the value for 3rd_smzdm.article_url
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleUrl(String articleUrl) {
        this.articleUrl = articleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_price
     *
     * @return the value of 3rd_smzdm.article_price
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticlePrice() {
        return articlePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_price
     *
     * @param articlePrice the value for 3rd_smzdm.article_price
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticlePrice(String articlePrice) {
        this.articlePrice = articlePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.article_favorite
     *
     * @return the value of 3rd_smzdm.article_favorite
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getArticleFavorite() {
        return articleFavorite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.article_favorite
     *
     * @param articleFavorite the value for 3rd_smzdm.article_favorite
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setArticleFavorite(String articleFavorite) {
        this.articleFavorite = articleFavorite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.time_sort
     *
     * @return the value of 3rd_smzdm.time_sort
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getTimeSort() {
        return timeSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.time_sort
     *
     * @param timeSort the value for 3rd_smzdm.time_sort
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setTimeSort(String timeSort) {
        this.timeSort = timeSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.user_smzdm_id
     *
     * @return the value of 3rd_smzdm.user_smzdm_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getUserSmzdmId() {
        return userSmzdmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.user_smzdm_id
     *
     * @param userSmzdmId the value for 3rd_smzdm.user_smzdm_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setUserSmzdmId(String userSmzdmId) {
        this.userSmzdmId = userSmzdmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.tag
     *
     * @return the value of 3rd_smzdm.tag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.tag
     *
     * @param tag the value for 3rd_smzdm.tag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.sort
     *
     * @return the value of 3rd_smzdm.sort
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.sort
     *
     * @param sort the value for 3rd_smzdm.sort
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.user_id
     *
     * @return the value of 3rd_smzdm.user_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.user_id
     *
     * @param userId the value for 3rd_smzdm.user_id
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.push_flag
     *
     * @return the value of 3rd_smzdm.push_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public Integer getPushFlag() {
        return pushFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.push_flag
     *
     * @param pushFlag the value for 3rd_smzdm.push_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setPushFlag(Integer pushFlag) {
        this.pushFlag = pushFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.recommend_flag
     *
     * @return the value of 3rd_smzdm.recommend_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getRecommendFlag() {
        return recommendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.recommend_flag
     *
     * @param recommendFlag the value for 3rd_smzdm.recommend_flag
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setRecommendFlag(String recommendFlag) {
        this.recommendFlag = recommendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 3rd_smzdm.content
     *
     * @return the value of 3rd_smzdm.content
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 3rd_smzdm.content
     *
     * @param content the value for 3rd_smzdm.content
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    public String getTargetTitle() {
        return this.articleTitle;
    }

    public Integer getTargetTitleId() {
        return this.id;
    }

    public String getBehaviorId() {
        return  BehaviorContent.SMZDM.getPrefix()+this.id;
    }
}