package com.content.train.dto.mapper.train;

import com.content.train.dto.train.BaiduJoke;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BaiduJokeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_baidu_api_joke
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_baidu_api_joke
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int insert(BaiduJoke record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_baidu_api_joke
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int insertSelective(BaiduJoke record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_baidu_api_joke
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    BaiduJoke selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_baidu_api_joke
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int updateByPrimaryKeySelective(BaiduJoke record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_baidu_api_joke
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int updateByPrimaryKey(BaiduJoke record);

    int getMaxId();

    List<BaiduJoke> selectByRange(@Param("id")int firstId , @Param("pageSize")int pageSize);
}