package com.content.train.dto.mapper.train;

import com.content.train.dto.train.ChanYouJi;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ChanYouJiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_chanyouji
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_chanyouji
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int insert(ChanYouJi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_chanyouji
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int insertSelective(ChanYouJi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_chanyouji
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    ChanYouJi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_chanyouji
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int updateByPrimaryKeySelective(ChanYouJi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_chanyouji
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ChanYouJi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_chanyouji
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int updateByPrimaryKey(ChanYouJi record);


    int getMaxId();

    List<ChanYouJi> selectByRange(@Param("id")int firstId , @Param("pageSize")int pageSize);
}