package com.content.train.dto.mapper.train;

import com.content.train.dto.train.ItemSimiScore;
import com.content.train.dto.train.ItemSimiScoreKey;

public interface ItemSimiScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_simi_score
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    int deleteByPrimaryKey(ItemSimiScoreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_simi_score
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    int insert(ItemSimiScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_simi_score
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    int insertSelective(ItemSimiScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_simi_score
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    ItemSimiScore selectByPrimaryKey(ItemSimiScoreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_simi_score
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    int updateByPrimaryKeySelective(ItemSimiScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_simi_score
     *
     * @mbggenerated Thu Aug 04 23:33:40 CST 2016
     */
    int updateByPrimaryKey(ItemSimiScore record);
}