package com.content.train.dto.mapper.train;

import com.content.train.dto.train.MiaoPaiVideo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MiaoPaiVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_miaopai_video
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_miaopai_video
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int insert(MiaoPaiVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_miaopai_video
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int insertSelective(MiaoPaiVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_miaopai_video
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    MiaoPaiVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_miaopai_video
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int updateByPrimaryKeySelective(MiaoPaiVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_miaopai_video
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int updateByPrimaryKey(MiaoPaiVideo record);


    int getMaxId();

    List<MiaoPaiVideo> selectByRange(@Param("id")int firstId , @Param("pageSize")int pageSize);
}