package com.content.train.dto.mapper.train;

import com.content.train.dto.train.SmZdm;

public interface SmZdmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_smzdm
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_smzdm
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int insert(SmZdm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_smzdm
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int insertSelective(SmZdm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_smzdm
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    SmZdm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_smzdm
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int updateByPrimaryKeySelective(SmZdm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_smzdm
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(SmZdm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 3rd_smzdm
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int updateByPrimaryKey(SmZdm record);
}