package com.content.train.dto.mapper.train;

import com.content.train.dto.train.UserBehavior;

public interface UserBehaviorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxtk_user_behavior
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxtk_user_behavior
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int insert(UserBehavior record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxtk_user_behavior
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int insertSelective(UserBehavior record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxtk_user_behavior
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    UserBehavior selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxtk_user_behavior
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int updateByPrimaryKeySelective(UserBehavior record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxtk_user_behavior
     *
     * @mbggenerated Tue Aug 02 17:37:27 CST 2016
     */
    int updateByPrimaryKey(UserBehavior record);
}